apiVersion: "search.pravega.io/v1alpha1"
kind: "PravegaSearch"
metadata:
  name: "pravega-search-cluster"
spec:
  pravegaControllerIP: pravega-pravega-controller
  pSearchController:
    replicas: 1
    image:
      repository: jirnsr/controller
      tag: latest
      pullPolicy: Always
  resthead:
    replicas: 1
    image:
      repository: jirnsr/resthead
      tag: latest
      pullPolicy: Always
  indexWorker:
    replicas: 1
    image:
      repository: jirnsr/indexworker
      tag: latest
      pullPolicy: Always
  queryWorker:
    replicas: 1
    image:
      repository: jirnsr/queryworker
      tag: latest
      pullPolicy: Always
  shardWorker:
    replicas: 1
    image:
      repository: jirnsr/shardworker
      tag: latest
      pullPolicy: Always
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:6.0.0-alpha1
          ports:
            - containerPort: 5601
              protocol: TCP
          env:
            - name: "ELASTICSEARCH_URL"
              value: "http://resthead-service:9098"
          command: [ "/bin/bash", "-c", "bin/kibana-plugin remove x-pack; bin/kibana -e http://resthead-service:9098"]

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: resthead
  name: resthead-service-external
spec:
  ports:
    - port: 9098
      targetPort: 9098
  selector:
    app: resthead
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: kibana
  name: kibana-service
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana
  type: LoadBalancer
