apiVersion: "search.pravega.io/v1alpha1"
kind: "PravegaSearch"
metadata:
  name: "pravega-search-cluster"
spec:
  pravegaControllerIP: pravega-pravega-controller
  pSearchController:
    replicas: 1
    image:
      repository: jirnsr/controller
      tag: latest
      pullPolicy: Always
  resthead:
    replicas: 1
    image:
      repository: jirnsr/resthead
      tag: latest
      pullPolicy: Always
  indexWorker:
    replicas: 1
    image:
      repository: jirnsr/indexworker
      tag: latest
      pullPolicy: Always
  queryWorker:
    replicas: 1
    image:
      repository: jirnsr/queryworker
      tag: latest
      pullPolicy: Always
  shardWorker:
    replicas: 1
    image:
      repository: jirnsr/shardworker
      tag: latest
      pullPolicy: Always