# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 0.5.0-2299.8779f22-0.9.0-026.4b08238
zookeeperUri: zk-client:2181

externalAccess:
  enabled: false
  type: LoadBalancer

bookkeeper:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
  replicas: 3
  storage:
    ledgerVolumeRequest: 30Gi
    journalVolumeRequest: 80Gi
    indexVolumeRequest: 50Gi
  autoRecovery: true

pravega:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/nautilus-pravega
  controllerReplicas: 2
  segmentStoreReplicas: 3
  debugLogging: false
  cacheVolumeRequest: 50Gi
  tier2: pravega-tier2
