kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jmeter-task
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter
spec:
  template:
    metadata:
      name: jmeter
    spec:
      restartPolicy: Never
      containers:
      - name: jmeter
        image: jirnsr/jmeter
        command:
          - "/apache-jmeter-5.0/bin/jmeter"
          - "-n"
          - "-t"
          - "/TestPlan.jmx"
          - "-l"
          - "/output/log.csv"
          - "-j"
          - "/output/joker"
        volumeMounts:
        - name: data
          mountPath: /output
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: jmeter-task