# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pravegaControllerIP: pravega-pravega-controller

pSearchController:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/psearch-controller
    tag: 0.5.0
  replicas: 2

resthead:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/psearch-resthead
    tag: 0.5.0
  replicas: 2

indexWorker:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/psearch-indexworker
    tag: 0.5.0
  replicas: 2

queryWorker:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/psearch-queryworker
    tag: 0.5.0
  replicas: 2

shardWorker:
  image:
    repository: devops-repo.isus.emc.com:8116/nautilus/psearch-shardworker
    tag: 0.5.0
  replicas: 2