apiVersion: v1
kind: Service
metadata:
  #namespace: tick
  name: chronograf-ss
spec:
  clusterIP: None
  selector:
    app: chronograf
---
apiVersion: v1
kind: Service
metadata:
  #namespace: tick
  name: chronograf
spec:
  selector:
    app: chronograf
  ports:
  - name: api
    port: 80
    targetPort: api

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  #namespace: tick
  name: chronograf
spec:
  replicas: 1
  serviceName: chronograf-ss
  selector:
    matchLabels:
      app: chronograf
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: nfs
      resources:
        requests:
          storage: 10Gi
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: chronograf:latest
        command: ["chronograf"]
        args: ["--influxdb-url=http://influxdb.default.svc.cluster.local:8086", "--kapacitor-url=http://kapacitor.default.svc.cluster.local:9092"]
        ports:
        - name: api
          containerPort: 8888
        livenessProbe:
          httpGet:
            path: /ping
            port: api
        readinessProbe:
          httpGet:
            path: /ping
            port: api
        volumeMounts:
        - name: data
          mountPath: /var/lib/chronograf
        #resources:
        #  requests:
        #    cpu: 100m
        #    memory: 1000Mi
        #  limits:
        #    cpu: 2000m
        #    memory: 1000Mi